# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170212_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='most_recent_post_first',
            field=models.BooleanField(default=True),
        ),
    ]
