# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 17:18
from __future__ import unicode_literals

import blog.models
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170223_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagewithhtml',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('rich_text', wagtail.wagtailcore.blocks.RichTextBlock(icon='doc-full', label='Rich Text')), ('code_python', blog.models.CodeBlockPython()), ('code_nohighlight', blog.models.CodeBlockNoHighlight()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock(icon='site', label='HTML')))),
        ),
    ]
