# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170223_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPageWithHtml',
            new_name='BlogPageWithCode',
        ),
    ]
